[package]
name = "simscript-physics"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = {version = "0.29.2", features=["approx"]}
overload = "0.1.1"
approx = "0.5.1"
approx_derive = {path="./approx_derive"}

[workspace]
members = [
    "approx_derive",
]
